name: Update Translations
on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
    update:
        name: Update translations
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node v18
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  cache: "yarn"

            - name: Install dependencies
              run: yarn

            - name: Get translations
              run: yarn translations

            - name: Commit updates
              shell: bash
              env:
                GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
              run: |
                git config user.name "Github Actions"
                git config user.email "$GIT_EMAIL"
                git fetch
                git checkout data
                git add --all .
                git commit -m "chore(languageNames): update language translations"
                git push -u
              continue-on-error: true
